name: TestConfigurationSample

on:
  push:
    branches:
      - main
    paths:
      - 'TestConfigurationSample/**'
  pull_request:
    paths:
      - 'TestConfigurationSample/**'

env:
  SAMPLE_PATH: TestConfigurationSample

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project and run local tests
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew spotlessCheck assembleDebug lintDebug testDebug --stacktrace --no-build-cache --rerun-tasks

  gradleManagedVirtualDevicesTest:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key for Gradle cache
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Cache pixel2api30 system image
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/gradle/avd/dev30_aosp_x86_Pixel_2.*
            ~/.android/gradle/avd/dev30_aosp_x86_64_Pixel_2.*
          key: pixel2api30

      - name: Cache pixel2api26 system image
        uses: actions/cache@v2
        with:
          path: ~/.android/gradle/avd/dev26_aosp_x86_Pixel_2.*
          key: pixel2api26

      - name: Cache nexus9api29 system image
        uses: actions/cache@v2
        with:
          path: ~/.android/gradle/avd/dev29_aosp_x86_Nexus_9.*
          key: nexus9api29

      - name: Run all tests
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew pixel2api30DebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=com.example.android.testing.testconfigurationsample.TestDeviceLargeScreen -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" --info

      - name: Run regression tests
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew -i pixel2api26DebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.example.android.testing.testconfigurationsample.TestDeviceApi26 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Run large screen tests
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew -i nexus9api29DebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.example.android.testing.testconfigurationsample.TestDeviceLargeScreen -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports/androidTests

      - name: Upload emulator logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: emulator-logs
          path: |
            ${{ env.SAMPLE_PATH }}/app/build/outputs/androidTest-results/managedDevice/**
            !${{ env.SAMPLE_PATH }}/**/*:*.xml
            !${{ env.SAMPLE_PATH }}/**/*|*
